import Head from "next/head";
import { Inter } from "@next/font/google";
import Image from "next/legacy/image";

import { AiFillFolderOpen, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import { FaPhp, FaHtml5, FaCss3Alt } from "react-icons/fa";
import { DiDjango, DiBootstrap } from "react-icons/di";

import p1image1 from "../public/project1/p1_menu.png";
import p1image2 from "../public/project1/p1_orderpage.png";
import p1image3 from "../public/project1/p1_admindashboard.png";

import p2image1 from "../public/project2/p2_catalog.png";
import p2image2 from "../public/project2/p2_bookdetail.png";
import p2image3 from "../public/project2/p2_createbook.png";
import p2image4 from "../public/project2/p2_profile.png";

import profile from "../public/profile.jpg";
import { useState } from "react";
import ScrollToTop from "react-scroll-to-top";

import React, { Component } from "react";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { Carousel } from "react-responsive-carousel";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const [darkMode, setDarkMode] = useState(false);
	return (
		<div className={darkMode ? "dark" : ""}>
			<Head>
				<title>Razzeq Roslan</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="bg-white px-10 md:px-20 lg:px-40">
				<section className="min-h-screen">
					<nav className="mb-12 flex justify-between py-10">
						<h1 className="flex items-center font-burtons text-xl">
							builtbyR
						</h1>
						<ul className="flex items-center">
							<li>
								<AiFillFolderOpen
									onClick={() => setDarkMode(!darkMode)}
									className="cursor-pointer text-2xl"
								/>
							</li>
							<button className="ml-8 rounded-md bg-gradient-to-r from-gray-400 to-gray-700 px-4 py-2 text-white">
								<a href="#">Resume</a>
							</button>
						</ul>
					</nav>
					<div className="mt-auto p-10 pb-10 text-center">
						<h2 className="lg:text-12xl py-2 text-5xl font-medium text-gray-800 md:text-6xl">
							Razzeq
						</h2>
						<h3 className="py-2 text-2xl dark:text-gray-500 md:text-3xl">
							Software Engineer
						</h3>
						<p className="text-md text-grey-800 mx-auto max-w-lg py-5 leading-8 md:text-xl">
							Love all things about backend technologies and
							learning about them !
						</p>
					</div>
					<div className="flex justify-center gap-16 py-3 text-5xl text-gray-600">
						<a
							href="https://www.linkedin.com/in/razzeq/"
							target="_blank"
							rel="noopener noreferrer"
						>
							<AiFillLinkedin />
						</a>
						<a
							href="https://github.com/rrzq"
							target="_blank"
							rel="noopener noreferrer"
						>
							<AiFillGithub />
						</a>
					</div>
					<div className="relative mx-auto mt-20 h-80 w-80 overflow-hidden rounded-full md:h-96 md:w-96">
						<Image
							src={profile}
							layout="fill"
							objectFit="cover"
							alt=""
						/>
					</div>
				</section>

				{/* Project Section */}
				<section>
					<div>
						<h3 className="py-1 text-3xl">Projects</h3>
						<p className="text-md py-2 leading-8 text-gray-800">
							Here, you will find a collection of projects that
							showcase my skills. Using programming languages such
							as Python and PHP (for now), I have implemented best
							practices in software engineering, including version
							control, testing, and documentation, to ensure
							high-quality final products.
						</p>
					</div>
					<div className="gap-10 md:flex lg:flex">
						<div className="my-10 rounded-xl p-10 text-center shadow-lg">
							<div>
								<Carousel showThumbs={false}>
									<div>
										<Image
											src={p2image1}
											alt="Catalog View"
										/>
										<p className="legend">
											Book Catalog View
										</p>
									</div>
									<div>
										<Image
											src={p2image2}
											alt="Book Detail"
										/>
										<p className="legend">
											Book Detail View
										</p>
									</div>
									<div>
										<Image
											src={p2image3}
											alt="Create Book"
										/>
										<p className="legend">
											Book Create View
										</p>
									</div>
									{/* <div>
										<Image src={p2image4} />
										<p className="legend">Image 1</p>
									</div> */}
								</Carousel>
							</div>
							<h3 className="pt-8 pb-2 text-lg font-medium">
								Library Systems
							</h3>
							<div className="flex items-center justify-center gap-1">
								<a
									href="https://github.com/rrzq/django-library-systems"
									target="_blank"
									rel="noopener noreferrer"
									className="text-gray-700"
								>
									<AiFillGithub />
								</a>
								<a
									href="https://github.com/rrzq/django-library-systems"
									target="_blank"
									rel="noopener noreferrer"
									className="text-gray-700"
								>
									Github
								</a>
							</div>
							<p className="py-2">
								Tried going all-in by building a full stack
								webapp, currently a work-in-progress, still
								trying to finish it and figuring out
								Django&apos;s MTV structure
							</p>
							<h4 className="py-4 text-gray-600">Technologies</h4>
							<div className="flex justify-center gap-16 py-3 text-5xl text-gray-600">
								<a>
									<DiDjango />
								</a>
								<a>
									<DiBootstrap />
								</a>
							</div>
						</div>
						<div className="my-10 rounded-xl p-10 text-center shadow-lg">
							<div>
								<Carousel showThumbs={false}>
									<div>
										<Image src={p1image1} alt="Main menu" />
										<p className="legend">Main menu</p>
									</div>
									<div>
										<Image
											src={p1image2}
											alt="Order Page"
										/>
										<p className="legend">Order Page</p>
									</div>
									<div>
										<Image
											src={p1image3}
											alt="Admin Dashboard"
										/>
										<p className="legend">
											Admin Dashboard
										</p>
									</div>
								</Carousel>
							</div>
							<h3 className="pt-8 pb-2 text-lg font-medium">
								Food Ordering Systems
							</h3>
							<div className="flex items-center justify-center gap-1">
								<a
									href="https://github.com/rrzq/php-foodorderingsystem"
									target="_blank"
									rel="noopener noreferrer"
									className="text-gray-700"
								>
									<AiFillGithub />
								</a>
								<a
									href="https://github.com/rrzq/php-foodorderingsystem"
									target="_blank"
									rel="noopener noreferrer"
									className="text-gray-700"
								>
									Github
								</a>
							</div>
							<p className="py-2">
								Project that was built for my final assesment
								during my studies, handcrafted without using any
								CSS library and vanilla PHP. Not my best work, I
								promise you.
							</p>
							<h4 className="py-4 text-gray-600">Technologies</h4>
							<div className="flex justify-center gap-16 py-3 text-5xl text-gray-600">
								<a>
									<FaPhp />
								</a>
								<a>
									<FaHtml5 />
								</a>
								<a>
									<FaCss3Alt />
								</a>
							</div>
						</div>
					</div>
				</section>

				{/* Portfolio Section WIP */}
				{/* <section>
					<div>
						<h3 className="py-1 text-3xl">Portfolio</h3>
						<p className="text-md py-2 leading-8 text-gray-800">
							Lorem ipsum dolor sit amet consectetur adipisicing
							elit. Ipsam voluptates rem placeat sed iste possimus
							illo, ex cumque vitae. Voluptatibus maxime alias
							rerum nam inventore facilis molestias in ex quo!
						</p>
					</div>
					<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
						<div className="flex-1 basis-1/3">
							<Image
								src={}
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout={"responsive"}
							/>
						</div>
						<div className="flex-1 basis-1/3">
							<Image
								src={}
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout={"responsive"}
							/>
						</div>
						<div className="flex-1 basis-1/3">
							<Image
								src={}
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout={"responsive"}
							/>
						</div>
						<div className="flex-1 basis-1/3">
							<Image
								src={}
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout={"responsive"}
							/>
						</div>
					</div>
				</section> */}
			</main>
			<ScrollToTop
				smooth
				className="mt-auto flex animate-pulse justify-center pt-1"
			/>
		</div>
	);
}
