import Head from "next/head";
import { Inter } from "@next/font/google";
import { AiFillFolderOpen, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/legacy/image";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import profile from "../public/profile.JPG";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const [darkMode, setDarkMode] = useState(false);
	return (
		<div className={darkMode ? "dark" : ""}>
			<Head>
				<title>Razzeq Roslan</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="bg-white px-10 md:px-20 lg:px-40">
				<section className="min-h-screen">
					<nav className="py-10 mb-12 flex justify-between ">
						<h1 className="text-xl font-burtons">developedbyR</h1>
						<ul className="flex items-center">
							<li>
								<AiFillFolderOpen
									onClick={() => setDarkMode(!darkMode)}
									className="cursor-pointer text-2xl"
								/>
							</li>
							<li className="bg-gradient-to-r from-gray-400 to-gray-700 text-white px-4 py-2 rounded-md ml-8">
								<a href="#">Resume</a>
							</li>
							<li></li>
						</ul>
					</nav>
					<div className="text-center p-10">
						<h2 className="text-5xl py-2 text-gray-800 font-medium md:text-6xl lg:text-12xl">
							Mohd Razzeq
						</h2>
						<h3 className="text-2xl py-2 md:text-3xl dark:text-gray-500">
							Software Engineer
						</h3>
						<p className="text-md py-5 leading-8 text-grey-800 md:text-xl max-w-lg mx-auto">
							Love all things about backend technologies and
							learning about them !
						</p>
					</div>
					<div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
						<a
							href="https://www.linkedin.com/in/razzeq/"
							target="_blank"
							rel="noopener noreferrer"
						>
							<AiFillLinkedin />
						</a>
						<a
							href="https://github.com/rrzq"
							target="_blank"
							rel="noopener noreferrer"
						>
							<AiFillGithub />
						</a>
					</div>
					<div className="relative mx-auto bg-gradient-to-b from-gray-600 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 ">
						<Image src={profile} layout="fill" objectFit="cover" />
					</div>
				</section>
				{/*  */}
				<section>
					<div>
						<h3 className="text-3xl py-1">Projects</h3>
						<p className="text-md py-2 leading-8 text-gray-800">
							Lorem ipsum dolor sit amet consectetur adipisicing
							elit. Ipsam voluptates rem placeat sed iste possimus
							illo, ex cumque vitae. Voluptatibus maxime alias
							rerum nam inventore facilis molestias in ex quo!
						</p>
					</div>
					<div className="lg:flex gap-10">
						<div className="text-center shadow-lg p-10 rounded-xl my-10">
							<Image
								className="mx-auto"
								src={design}
								width={100}
								height={100}
							/>
							<h3 className="text-lg font-medium pt-8 pb-2">
								Library Systems
							</h3>
							<p className="py-2">
								Lorem ipsum, dolor sit amet consectetur
								adipisicing elit. Perferendis eos, neque nemo
								dolores, molestias aliquid laborum aspernatur
								obcaecati fugit ullam accusamus. Illum quo
								praesentium ut expedita sequi dolor ratione
								quam.
							</p>
							<h4 className="py-4 text-teal-600">Technologies</h4>
							<p className="text-gray-800 py-1">Django</p>
						</div>
						<div className="text-center shadow-lg p-10 rounded-xl my-10">
							<Image
								className="mx-auto"
								src={consulting}
								width={100}
								height={100}
							/>
							<h3 className="text-lg font-medium pt-8 pb-2">
								Library Systems
							</h3>
							<p className="py-2">
								Lorem ipsum, dolor sit amet consectetur
								adipisicing elit. Perferendis eos, neque nemo
								dolores, molestias aliquid laborum aspernatur
								obcaecati fugit ullam accusamus. Illum quo
								praesentium ut expedita sequi dolor ratione
								quam.
							</p>
							<h4 className="py-4 text-teal-600">Technologies</h4>
							<p className="text-gray-800 py-1">Django</p>
						</div>
						<div className="text-center shadow-lg p-10 rounded-xl my-10">
							<Image
								className="mx-auto"
								src={code}
								width={100}
								height={100}
							/>
							<h3 className="text-lg font-medium pt-8 pb-2">
								Library Systems
							</h3>
							<p className="py-2">
								Lorem ipsum, dolor sit amet consectetur
								adipisicing elit. Perferendis eos, neque nemo
								dolores, molestias aliquid laborum aspernatur
								obcaecati fugit ullam accusamus. Illum quo
								praesentium ut expedita sequi dolor ratione
								quam.
							</p>
							<h4 className="py-4 text-teal-600">Technologies</h4>
							<p className="text-gray-800 py-1">Django</p>
						</div>
					</div>
				</section>
				<section>
					<div>
						<h3 className="text-3xl py-1">Portfolio</h3>
						<p className="text-md py-2 leading-8 text-gray-800">
							Lorem ipsum dolor sit amet consectetur adipisicing
							elit. Ipsam voluptates rem placeat sed iste possimus
							illo, ex cumque vitae. Voluptatibus maxime alias
							rerum nam inventore facilis molestias in ex quo!
						</p>
					</div>
					<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
						<div className="basis-1/3 flex-1">
							<Image
								src={web1}
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout={"responsive"}
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								src={web2}
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout={"responsive"}
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								src={web3}
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout={"responsive"}
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								src={web4}
								className="rounded-lg object-cover"
								width={"100%"}
								height={"100%"}
								layout={"responsive"}
							/>
						</div>
					</div>
				</section>
			</main>
		</div>
	);
}
